spring:
  datasource:
    username: root
    password: 76#Ht67
    url: jdbc:mysql://121.43.148.120:3306/learnjdbc?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8089
