# DataSource Config
spring:
  datasource:
    username: root
    password: 76#Ht67
    url: jdbc:mysql://121.43.148.120:3306/studentmanager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8087
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoint:
    # Metrics 端点配置项
    metrics:
      enabled: true # 是否开启。默认为 true 开启。
  # Metrics 的具体配置项，对应 MetricsProperties 配置类
  metrics:
    # 设置指定前缀的指标是否开启
    enable:
      xxx: false
    # 通用 tag
    tags:
      application: demo-application

  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      base-path: /actuator # Actuator 提供的 API 接口的根目录。默认为 /actuator
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        exclude: # 在 include 的基础上，需要排除的端点。通过设置 * ，可以排除所有端点




